plugins {
    id 'multiloader-loader'
    id 'com.github.johnrengelman.shadow'
    id 'me.modmuss50.mod-publish-plugin'
    id 'fabric-loom'
}

fabricApi {
    configureDataGeneration()
}


dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"


    //Mod Menu
    modImplementation("com.terraformersmc:modmenu:${mod_menu_version}")

    //JEI
    modCompileOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    //REI
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
    //EMI
    modCompileOnly "dev.emi:emi-fabric:${emi_version}+${minecraft_version}:api"

    switch (nei) {
        case "JEI":
            modLocalRuntime "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
            break
        case "REI":
            modLocalRuntime "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
            break
        case "EMI":
            modLocalRuntime "dev.emi:emi-fabric:${emi_version}+${minecraft_version}"
            break

    }

    //Jade
    modImplementation ("maven.modrinth:jade:${jade_version}+fabric")

    //Lootr
    modImplementation "noobanidus.mods.lootr:lootr-fabric:${lootr_version}"
    modRuntimeOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}")


    //
    // NightConfig
    implementation 'com.electronwill.night-config:core:3.6.6'
    implementation 'com.electronwill.night-config:toml:3.6.6'
    shadow 'com.electronwill.night-config:core:3.6.6'
    shadow 'com.electronwill.night-config:toml:3.6.6'

}

shadowJar {
    dependsOn jar
    configurations = [project.configurations.shadow]
    destinationDirectory.set(file("${project.layout.buildDirectory.get()}/devlibs"))
    archiveClassifier.set("dev")
    relocate "com.electronwill.nightconfig", "${group}.shadow.nightconfig"
}
remapJar.dependsOn(shadowJar)

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}


configurePublishing(project, [
        loaderName     : 'Fabric',
        gameLoader     : 'fabric',
        releaseType    : rootProject.fabric_release_type,
        publicationTask: 'remapJar',
        requiredMods   : ['fabric-api']
])