plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' apply(false)
    id 'net.neoforged.moddev.legacyforge' version '2.0.77' apply(false)
    id 'com.github.johnrengelman.shadow' version '7.1.2' apply(false)
}
allprojects {
    repositories {
        maven {
            url = "https://modmaven.dev"
        }
        maven {
            url 'https://maven.blamejared.com/'
        }
        maven {
            url "https://maven.shedaniel.me"
        }
        maven {
            url "https://api.modrinth.com/maven"
        }
        maven {
            url = "https://maven.terraformersmc.com/"
        }
        maven {
            url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/"
        }
    }
}