# Release
version=4.3.01
group=com.nine.travelerscompass
modrinth_project_id=WJLLirmC
curseforge_project_id=954415
fabric_release_type=release
neoforge_release_type=release

# Meta
mod_id=travelerscompass
mod_name=Traveler's Compass
mod_author=Nine
description=Compass for finding mobs and blocks.
license=LGPL v3.0
credits=

# Minecraft Target
minecraft_version=26.2
display_minecraft_version=26.2
publish_game_versions=26.2
minecraft_version_range=[26.2, 27)
minecraft_version_constraint=26.2.x
java_version=25

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge/
neoforge_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.2-1

# Enabled Compat
nei=
waila=JADE

# Compat Versions
jei_version=29.2.0.20
rei_version=
emi_version=
jade_version=26.2.0
mod_menu_version=20.0.0-beta.2
lootr_version=
top_curse_project_id=
top_curse_file_id=

# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
