# Release
version=4.3.02
group=com.nine.travelerscompass
modrinth_project_id=WJLLirmC
curseforge_project_id=954415
fabric_release_type=release
neoforge_release_type=release

# Meta
mod_id=travelerscompass
mod_name=Traveler's Compass
mod_author=Nine
description=Compass for finding mobs and blocks.
license=LGPL v3.0
credits=

# Minecraft Target
minecraft_version=26.1
display_minecraft_version=26.1.2
publish_game_versions=26.1,26.1.1,26.1.2
minecraft_version_range=[26.1, 26.2)
minecraft_version_constraint=26.1.x
java_version=25

# Loader Versions
fabric_loader_version=0.18.6
fabric_version=0.152.1+26.1.2
neoforge_version=26.1.0.8-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.1-1

# Enabled Compat
nei=JEI
waila=JADE

# Compat Versions
jei_version=29.2.0.21
rei_version=26.1.818
emi_version=
jade_fabric_version=26.1.4
jade_neoforge_version=26.1.3
mod_menu_version=18.0.0-beta.1
lootr_version=1.21.35.106
cloth_config_version=26.1.154
architectury_fabric_version=20.0.6
architectury_neoforge_version=20.0.6
top_curse_project_id=
top_curse_file_id=

# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
