# Release
version=4.3.01
group=com.nine.travelerscompass
modrinth_project_id=WJLLirmC
curseforge_project_id=954415
fabric_release_type=release
neoforge_release_type=release

# Meta
mod_id=travelerscompass
mod_name=Traveler's Compass
mod_author=Nine
description=Compass for finding mobs and blocks.
license=LGPL v3.0
credits=

# Minecraft Target
minecraft_version=26.1
display_minecraft_version=26.1.1
publish_game_versions=26.1,26.1.1
minecraft_version_range=[26.1, 26.2)
minecraft_version_constraint=26.1.x
java_version=25

# Loader Versions
fabric_loader_version=0.18.4
fabric_version=0.145.2+26.1.1
neoforge_version=26.1.0.8-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.1-1

# Enabled Compat
nei=JEI
waila=JADE

# Compat Versions
jei_version=29.2.0.20
rei_version=
emi_version=
jade_version=26.0.5
mod_menu_version=18.0.0-alpha.8
lootr_version=
top_curse_project_id=
top_curse_file_id=

# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
