plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.shedaniel.unified-publishing'
}


neoForge {
    version = neoforge_version

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }

        client {
            client()
            gameDirectory = mkdir(file("runs/client"))
        }

        server {
            server()
            gameDirectory = mkdir(file("runs/server"))
        }
    }

    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}


dependencies {

    // Jei
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"

    // REI
    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}"
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "dev.architectury:architectury-neoforge:${architectury_neoforge_version}"

    // Jade
    compileOnly "maven.modrinth:jade:${jade_neoforge_version}+neoforge"

    // Lootr
    compileOnly "maven.modrinth:lootr:${lootr_version}"

    switch (nei) {
        case "JEI":
            runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
            break
        case "REI":
            runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
            runtimeOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
            runtimeOnly "dev.architectury:architectury-neoforge:${architectury_neoforge_version}"
            break
        case "EMI":
            break
    }

    switch (waila) {
        case "JADE":
            runtimeOnly "maven.modrinth:jade:${jade_neoforge_version}+neoforge"
            break
        case "TOP":

            break
    }

    runtimeOnly "maven.modrinth:lootr:${lootr_version}"
}


sourceSets.main.resources.srcDir 'src/generated/resources'

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
def markNeoForge = { String configName ->
    configurations.named(configName) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}

['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each(markNeoForge)

sourceSets.configureEach {
    [compileClasspathConfigurationName, runtimeClasspathConfigurationName, getTaskName(null, 'jarJar')]
            .each(markNeoForge)
}

configureUnifiedPublishing(project, [
        loaderName     : "NeoForge",
        gameLoader     : "neoforge",
        releaseType    : rootProject.neoforge_release_type,
        publicationTask: "jar"
])
