plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.shedaniel.unified-publishing'
}


neoForge {
    version = neoforge_version

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }

        client {
            client()
            gameDirectory = mkdir(file("runs/client"))
        }

        server {
            server()
            gameDirectory = mkdir(file("runs/server"))
        }
    }

    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}


dependencies {

    // Jei
//    implementation "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    // Jade
//    implementation "maven.modrinth:jade:${jade_version}+neoforge"
}


sourceSets.main.resources.srcDir 'src/generated/resources'

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
def markNeoForge = { String configName ->
    configurations.named(configName) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}

['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each(markNeoForge)

sourceSets.configureEach {
    [compileClasspathConfigurationName, runtimeClasspathConfigurationName, getTaskName(null, 'jarJar')]
            .each(markNeoForge)
}

configureUnifiedPublishing(project, [
        loaderName     : "NeoForge",
        gameLoader     : "neoforge",
        releaseType    : rootProject.neoforge_release_type,
        publicationTask: "jar"
])
